import { Complaint } from "./complain"

export const complaints: Complaint[] = [
  {
      id: "1",
      problems: "REQ-001",
      app: "Line",
      title: "ไฟถนนดับ",
      person: "สมชาย ใจดี",
      phone: "0812345678",
      status: "กำลังดำเนินการ",
      staff: "วิชัย มุ่งมั่น",
    },
    {
      id: "2",
      problems: "REQ-002",
      app: "Web",
      title: "ถนนเป็นหลุม",
      person: "พิมพ์ชนก แสงทอง",
      phone: "0823456789",
      status: "กำลังดำเนินการ",
      staff: "ศุภกร แสนดี",
    },
    {
      id: "3",
      problems: "REQ-003",
      app: "Line",
      title: "น้ำประปาไม่ไหล",
      person: "ณัฐพล บุญมี",
      phone: "0834567890",
      status: "ไม่รับเรื่อง",
      staff: "อาคม มีชัย",
    },
    {
      id: "4",
      problems: "REQ-004",
      app: "App",
      title: "ขยะล้นถัง",
      person: "อรทัย สุขใจ",
      phone: "0845678901",
      status: "กำลังดำเนินการ",
      staff: "มยุรี ทองใบ",
    },
    {
      id: "5",
      problems: "REQ-005",
      app: "Web",
      title: "ไฟส่องสว่างเสีย",
      person: "ธีรภัทร วงศ์ดี",
      phone: "0856789012",
      status: "กำลังดำเนินการ",
      staff: "กิตติ รุ่งเรือง",
    },
    {
      id: "6",
      problems: "REQ-006",
      app: "Line",
      title: "ท่อระบายน้ำตัน",
      person: "กนกพร สิงห์คำ",
      phone: "0867890123",
      status: "กำลังดำเนินการ",
      staff: "วิชัย มุ่งมั่น",
    },
    {
      id: "7",
      problems: "REQ-007",
      app: "App",
      title: "เสียงดังรบกวน",
      person: "ชัยวัฒน์ รัตนโชติ",
      phone: "0878901234",
      status: "ไม่รับเรื่อง",
      staff: "ศุภกร แสนดี",
    },
    {
      id: "8",
      problems: "REQ-008",
      app: "Web",
      title: "ต้นไม้ล้มกีดขวาง",
      person: "สุพัตรา นาคสกุล",
      phone: "0889012345",
      status: "กำลังดำเนินการ",
      staff: "อาคม มีชัย",
    },
    {
      id: "9",
      problems: "REQ-009",
      app: "Line",
      title: "ไฟฟ้าตกบ่อย",
      person: "ธนกร มั่นคง",
      phone: "0890123456",
      status: "ประเมินผลเสร็จสิ้น",
      staff: "มยุรี ทองใบ",
    },
    {
      id: "10",
      problems: "REQ-010",
      app: "App",
      title: "ถนนทรุดตัว",
      person: "รัตนา ศรีสุข",
      phone: "0801234567",
      status: "กำลังดำเนินการ",
      staff: "กิตติ รุ่งเรือง",
    },
    {
      id: "11",
      problems: "REQ-011",
      app: "Web",
      title: "น้ำขังหลังฝนตก",
      person: "สมชาย ใจดี",
      phone: "0812345678",
      status: "กำลังดำเนินการ",
      staff: "วิชัย มุ่งมั่น",
    },
    {
      id: "12",
      problems: "REQ-012",
      app: "Line",
      title: "ไฟหน้าซอยไม่ติด",
      person: "พิมพ์ชนก แสงทอง",
      phone: "0823456789",
      status: "ประเมินผลเสร็จสิ้น",
      staff: "ศุภกร แสนดี",
    },
    {
      id: "13",
      problems: "REQ-013",
      app: "App",
      title: "กลิ่นขยะรบกวน",
      person: "ณัฐพล บุญมี",
      phone: "0834567890",
      status: "กำลังดำเนินการ",
      staff: "อาคม มีชัย",
    },
    {
      id: "14",
      problems: "REQ-014",
      app: "Web",
      title: "ท่อแตกน้ำรั่ว",
      person: "อรทัย สุขใจ",
      phone: "0845678901",
      status: "กำลังดำเนินการ",
      staff: "มยุรี ทองใบ",
    },
    {
      id: "15",
      problems: "REQ-015",
      app: "Line",
      title: "สายไฟห้อยต่ำ",
      person: "ธีรภัทร วงศ์ดี",
      phone: "0856789012",
      status: "กำลังดำเนินการ",
      staff: "กิตติ รุ่งเรือง",
    },
    {
      id: "16",
      problems: "REQ-016",
      app: "App",
      title: "ทางเท้าชำรุด",
      person: "กนกพร สิงห์คำ",
      phone: "0867890123",
      status: "ประเมินผลเสร็จสิ้น",
      staff: "วิชัย มุ่งมั่น",
    },
    {
      id: "17",
      problems: "REQ-017",
      app: "Web",
      title: "เสียงก่อสร้างกลางคืน",
      person: "ชัยวัฒน์ รัตนโชติ",
      phone: "0878901234",
      status: "ไม่รับเรื่อง",
      staff: "ศุภกร แสนดี",
    },
    {
      id: "18",
      problems: "REQ-018",
      app: "Line",
      title: "น้ำไหลอ่อน",
      person: "สุพัตรา นาคสกุล",
      phone: "0889012345",
      status: "กำลังดำเนินการ",
      staff: "อาคม มีชัย",
    },
    {
      id: "19",
      problems: "REQ-019",
      app: "App",
      title: "ไฟสัญญาณเสีย",
      person: "ธนกร มั่นคง",
      phone: "0890123456",
      status: "กำลังดำเนินการ",
      staff: "มยุรี ทองใบ",
    },
    {
      id: "20",
      problems: "REQ-020",
      app: "Web",
      title: "ถนนลื่นอันตราย",
      person: "รัตนา ศรีสุข",
      phone: "0801234567",
      status: "กำลังดำเนินการ",
      staff: "กิตติ รุ่งเรือง",
    },
    {
      id: "21",
      problems: "REQ-021",
      app: "Line",
      title: "ฝาท่อหาย",
      person: "สมชาย ใจดี",
      phone: "0812345678",
      status: "ประเมินผลเสร็จสิ้น",
      staff: "วิชัย มุ่งมั่น",
    },
    {
      id: "22",
      problems: "REQ-022",
      app: "App",
      title: "น้ำท่วมขัง",
      person: "พิมพ์ชนก แสงทอง",
      phone: "0823456789",
      status: "กำลังดำเนินการ",
      staff: "ศุภกร แสนดี",
    },
    {
      id: "23",
      problems: "REQ-023",
      app: "Web",
      title: "ไฟดับทั้งซอย",
      person: "ณัฐพล บุญมี",
      phone: "0834567890",
      status: "กำลังดำเนินการ",
      staff: "อาคม มีชัย",
    },
    {
      id: "24",
      problems: "REQ-024",
      app: "Line",
      title: "ขยะไม่ได้เก็บ",
      person: "อรทัย สุขใจ",
      phone: "0845678901",
      status: "ประเมินผลเสร็จสิ้น",
      staff: "มยุรี ทองใบ",
    },
    {
      id: "25",
      problems: "REQ-025",
      app: "App",
      title: "ถนนแตกร้าว",
      person: "ธีรภัทร วงศ์ดี",
      phone: "0856789012",
      status: "กำลังดำเนินการ",
      staff: "กิตติ รุ่งเรือง",
    }
]