import type { Metadata } from "next";
import "./globals.css";
import { Inter} from "next/font/google";
import { Noto_Sans_Thai} from "next/font/google";

//import font
const inter = Inter({
  subsets: ["latin"],
});

const thaiFont = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
    <html
        lang="th"
        className={`${inter.className} ${thaiFont.className} h-full antialiased`}
    >
        <body className="min-h-screen">{children}</body>
    </html>
    );
}